---
version: "3"
services:
  server:
    hostname: pyserver
    build:
      context: ./server
      args:
        pyvers: 3.11-slim-bullseye
    image: maximba/pyserver:1.0.0
    secrets:
      - cert.pem
      - key.pem
      - root-ca.pem
    environment:
      - MX_domain=${MX_domain}
      - MX_keyfile=${MX_keyfile}
      - MX_certfile=${MX_certfile} 
      - MX_cafile=${MX_cafile}  
    ports:
      - '8443:8443'
      - '8080:8080'
    command: ["python","server.py"]

  client:
    hostname: pyclient
    links:
      - "server:${MX_domain}"
      - "server:server1.${MX_domain}"
      - "server:server2.${MX_domain}"
      - "server:server3.${MX_domain}"
    build:
      context: ./client
      args:
        pyvers: 3.11-slim-bullseye
    image: maximba/pyclient:1.0.0
    environment:
      - MX_domain=${MX_domain}
      - MX_cafile=${MX_cafile}
    command: ["python","client.py"]
    depends_on:
      - server

secrets:
  cert.pem:
    file: "${MX_certspath}/${MX_domain}/${MX_certfile}"
  key.pem:
    file: "${MX_certspath}/${MX_domain}/${MX_keyfile}"
  root-ca.pem:
    file: "${MX_certspath}/${MX_cafile}"
